# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [11]:
a = np.array ([0,1,2,3,4])
b = np.array ([5,6,7,8,9])
np.vstack ((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [12]:
a = np.array ([0,1,2,3,4])
b = np.array ([5,6,7,8,9])
np.hstack ((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [17]:
m = np.array([[1,2] , [3,4] , [5,6]])
m.flatten()

array([1, 2, 3, 4, 5, 6])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [9]:
import numpy as np
z = np.array([[ 0, 1, 89],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

z.flatten()

array([ 0,  1, 89,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [10]:
z.reshape(5,3)

array([[ 0,  1, 89],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [6]:
x =  np.random.randint(1,high=5, size=5,dtype=int)
print(x)

[1 3 2 3 2]


# Question:8

### Create 5x6 an array and find the mean?

In [29]:
import numpy as np
x =  np.random.random((5,6))
print(x)
np.mean(x , dtype=np.float64)

[[0.11490029 0.95194952 0.25480027 0.18006575 0.55905049 0.90443142]
 [0.54915878 0.22958615 0.31379788 0.73960444 0.06630366 0.16803916]
 [0.88218872 0.23512132 0.65435582 0.9194224  0.84980193 0.86403791]
 [0.76291315 0.2060639  0.47437434 0.38711441 0.91082156 0.23874799]
 [0.70737143 0.49131476 0.9421857  0.4143896  0.1604226  0.34106457]]


0.5157799963868138

## Question:9

### Find the standard deviation of the previous array in Q8?

In [33]:
np.std(x) # standard deviation being calculated as a flattened array without axis given

0.29460974486061203

## Question:10

### Find the median of the previous array in Q8?

In [34]:
np.median(x)

0.482844548608074

## Question:11

### Find the transpose of the previous array in Q8?

In [36]:
print(x)
x.transpose()

[[0.11490029 0.95194952 0.25480027 0.18006575 0.55905049 0.90443142]
 [0.54915878 0.22958615 0.31379788 0.73960444 0.06630366 0.16803916]
 [0.88218872 0.23512132 0.65435582 0.9194224  0.84980193 0.86403791]
 [0.76291315 0.2060639  0.47437434 0.38711441 0.91082156 0.23874799]
 [0.70737143 0.49131476 0.9421857  0.4143896  0.1604226  0.34106457]]


array([[0.11490029, 0.54915878, 0.88218872, 0.76291315, 0.70737143],
       [0.95194952, 0.22958615, 0.23512132, 0.2060639 , 0.49131476],
       [0.25480027, 0.31379788, 0.65435582, 0.47437434, 0.9421857 ],
       [0.18006575, 0.73960444, 0.9194224 , 0.38711441, 0.4143896 ],
       [0.55905049, 0.06630366, 0.84980193, 0.91082156, 0.1604226 ],
       [0.90443142, 0.16803916, 0.86403791, 0.23874799, 0.34106457]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [49]:
y=np.array([[4,2,4,5],
           [8,1,1,1],
           [2,3,5,6],
           [5,6,7,8]])
z=np.diagonal(y)
print(sum(z))   # we can also use np.trace for adding diagonal like below, in that we will not sum at print stage

18


In [63]:
y=np.array([[4,2,4,5],
           [1,1,1,1],
           [2,3,5,6],
           [5,6,7,8]])
q = np.trace(y)
q

18

## Question:13

### Find the determinant of the previous array in Q12?

In [64]:
np.linalg.det(y)

2.9999999999999982

## Question:14

### Find the 5th and 95th percentile of an array?

In [68]:
np.percentile(y,95)

7.25

## Question:15

### How to find if a given array has any null values?

In [66]:
np.isnan(y)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])